In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print (torch.__version__)

2.0.0.dev20230207


In [7]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [35]:
#show the dimensions of the scalar
#shwos the number of dimensions
scalar.ndim

0

In [11]:
#method that we can use to get the item of the scalar
scalar.item()

7

In [15]:
#create a pytorch vector

vector = torch.tensor([7,7])
vector.ndim


1

In [16]:
vector.shape

torch.Size([2])

In [19]:
#create a matrix
matrix = torch.tensor([[2,3],
                       [4,5]])
matrix

tensor([[2, 3],
        [4, 5]])

In [20]:
matrix.shape

torch.Size([2, 2])

In [22]:
matrix.ndim

2

In [23]:
#what does ndim do
matrix[1]

tensor([4, 5])

In [26]:
#tensor
tensor = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [4,5,6]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [27]:
tensor.ndim

3

In [29]:
tensor.shape
#torch.Size([1, 3, 3]) we have a 1 tensor with a 3x3 matrix

torch.Size([1, 3, 3])

In [34]:
###random Tensors
#Create a random tensor of (3,4)
rTensor = torch.rand(3,4)
rTensor

tensor([[0.5756, 0.3179, 0.2749, 0.7363],
        [0.0271, 0.0180, 0.3815, 0.5529],
        [0.0647, 0.4191, 0.3144, 0.3843]])

In [39]:
#create a 3,4 matrix with 0s
zeroTensor = (torch.zeros(3,4))
zeroTensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])