In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print (torch.__version__)

2.0.0.dev20230207


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#show the dimensions of the scalar
#shwos the number of dimensions
scalar.ndim

0

In [5]:
#method that we can use to get the item of the scalar
scalar.item()

7

In [6]:
#create a pytorch vector

vector = torch.tensor([7,7])
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#create a matrix
matrix = torch.tensor([[2,3],
                       [4,5]])
matrix

tensor([[2, 3],
        [4, 5]])

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
matrix.ndim

2

In [11]:
#what does ndim do
matrix[1]

tensor([4, 5])

In [65]:
#tensor
tensor = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [4,5,6]]], dtype= torch.float32)
tensor

tensor([[[1., 2., 3.],
         [3., 4., 5.],
         [4., 5., 6.]]])

In [66]:
tensor.ndim

3

In [67]:
tensor.shape
#torch.Size([1, 3, 3]) we have a 1 tensor with a 3x3 matrix

torch.Size([1, 3, 3])

In [68]:
###random Tensors
#Create a random tensor of (3,4)
rTensor = torch.rand(3,4)
rTensor

tensor([[0.8547, 0.7870, 0.5995, 0.5451],
        [0.7973, 0.9470, 0.5712, 0.8403],
        [0.4941, 0.1472, 0.9759, 0.5389]])

In [69]:
#create a 3,4 matrix with 0s
zeroTensor = torch.zeros(3,4)
zeroTensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [70]:
#create a 3,4 matrix with 1s
oneTensor = torch.ones(3,4)
oneTensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [71]:
#what is the data type
oneTensor.dtype

torch.float32

In [72]:
# Creating a range of tensors and tensors like
one_to_ten = torch.arange(0,10)
one_to_ten



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
start_end = torch.arange(start=0, end=1000, step=23)
start_end

tensor([  0,  23,  46,  69,  92, 115, 138, 161, 184, 207, 230, 253, 276, 299,
        322, 345, 368, 391, 414, 437, 460, 483, 506, 529, 552, 575, 598, 621,
        644, 667, 690, 713, 736, 759, 782, 805, 828, 851, 874, 897, 920, 943,
        966, 989])

In [74]:
#create a tensor with teh same size as some else tensor
like_tensor = torch.zeros_like(one_to_ten)
like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
like_tensor_ones_matrix = torch.ones_like(tensor)
like_tensor_ones_matrix

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [76]:
#data types 
float_32_tensor = torch.tensor([1.,2.,3.],
                                dtype = None)
float_32_tensor.dtype

torch.float32

In [77]:
float_16_tensor = torch.tensor([1.,2.,3.],
                                dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [78]:
float_16_changer_tensor = float_32_tensor.type(torch.float16)
float_16_changer_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [79]:
random_tensor_10 = torch.rand(2,2)
random_tensor_10

tensor([[0.3023, 0.6475],
        [0.5827, 0.6946]])

In [80]:
print(f"shape of tensor is {random_tensor_10.shape} and the type of the tensor is {random_tensor_10.dtype}")

shape of tensor is torch.Size([2, 2]) and the type of the tensor is torch.float32


In [81]:
#manipulating tensors
tensor_10 = tensor +10
tensor_10

tensor([[[11., 12., 13.],
         [13., 14., 15.],
         [14., 15., 16.]]])

In [82]:
tensor_mul = torch.mul(tensor,10)
tensor_mul

tensor([[[10., 20., 30.],
         [30., 40., 50.],
         [40., 50., 60.]]])

In [83]:
#the multiplication aka element multiplication can also be done
tensor_mul = tensor * 10
tensor_mul

tensor([[[10., 20., 30.],
         [30., 40., 50.],
         [40., 50., 60.]]])

In [84]:
#matrix multiplication aka dot product
tensor_3x3 = torch.rand([3,3])
tensor_3x3b = torch.rand([3,3])
MM = torch.matmul(tensor_3x3,tensor_3x3b)
MM

tensor([[0.2031, 0.2739, 0.6760],
        [0.1659, 0.3655, 0.8070],
        [0.2508, 0.2413, 0.4270]])

In [85]:
%%time
 value = 0
 for i in range(len(tensor_3x3)) :
     value += tensor_3x3[i] * tensor_3x3b[i]
print(value)

tensor([0.3445, 0.2392, 0.4980])
CPU times: user 868 µs, sys: 784 µs, total: 1.65 ms
Wall time: 994 µs


In [86]:
%%time
MM = torch.matmul(tensor_3x3,tensor_3x3b)
MM

CPU times: user 35 µs, sys: 4 µs, total: 39 µs
Wall time: 39.3 µs


tensor([[0.2031, 0.2739, 0.6760],
        [0.1659, 0.3655, 0.8070],
        [0.2508, 0.2413, 0.4270]])

In [87]:
# another way to do matrix multiplication is via the @ operator
tensor_3x3b * tensor_3x3

tensor([[0.0553, 0.0268, 0.1933],
        [0.2264, 0.1729, 0.0061],
        [0.0628, 0.0395, 0.2986]])

In [88]:
# another way to do matrix multiplication is via torch.mm
torch.mm(tensor_3x3, tensor_3x3b)

tensor([[0.2031, 0.2739, 0.6760],
        [0.1659, 0.3655, 0.8070],
        [0.2508, 0.2413, 0.4270]])

In [89]:
#find the min
tensor.min()

tensor(1.)

In [90]:
#find the max
tensor.max()

tensor(6.)

In [91]:
#find the sum
tensor.sum()

tensor(33.)

In [94]:
#find the mean
tensor.type(torch.float64)
tensor.mean()

tensor(3.6667)

In [95]:
#finding the position of the min element in the tensor
tensor.argmin()

tensor(0)

In [96]:
#finding the positinio of the max element in the tensor
tensor.argmax()

tensor(8)

In [97]:
tensor

tensor([[[1., 2., 3.],
         [3., 4., 5.],
         [4., 5., 6.]]])

In [98]:
#reshape
#reshapes an input tensor to a desired shape



In [99]:
#view
#return a view of an input tensor of a certain shape but retain the same memory as the original tensor


In [100]:
#stacking
#combine different tensors together, whether the one on top (vstack) of the other or the one next to each other (hstack)


In [101]:
#squeeze
#removes all the 1 dimensions from the tensor


In [102]:
#unscqueeze
#ass a 1 dimension to a target tensor


In [103]:
#permute
#return a view of the input with dimensions permuted (swapped) in a certain way 


In [115]:
x_tensor = torch.arange(3.,13.)
x_tensor, x_tensor.shape

(tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]), torch.Size([10]))

In [116]:
x_reshaped = x_tensor.reshape(1,10) #add another dimension
x_reshaped, x_reshaped.shape


(tensor([[ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 10]))