In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print (torch.__version__)

1.14.0.dev20221102


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#show the dimensions of the scalar
#shwos the number of dimensions
scalar.ndim

0

In [5]:
#method that we can use to get the item of the scalar
scalar.item()

7

In [6]:
#create a pytorch vector

vector = torch.tensor([7,7])
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#create a matrix
matrix = torch.tensor([[2,3],
                       [4,5]])
matrix

tensor([[2, 3],
        [4, 5]])

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
matrix.ndim

2

In [11]:
#what does ndim do
matrix[1]

tensor([4, 5])

In [12]:
#tensor
tensor = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [4,5,6]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape
#torch.Size([1, 3, 3]) we have a 1 tensor with a 3x3 matrix

torch.Size([1, 3, 3])

In [15]:
###random Tensors
#Create a random tensor of (3,4)
rTensor = torch.rand(3,4)
rTensor

tensor([[0.0958, 0.5126, 0.3351, 0.5521],
        [0.0839, 0.9742, 0.8419, 0.0713],
        [0.2194, 0.6972, 0.4526, 0.0919]])

In [16]:
#create a 3,4 matrix with 0s
zeroTensor = torch.zeros(3,4)
zeroTensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
#create a 3,4 matrix with 1s
oneTensor = torch.ones(3,4)
oneTensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
#what is the data type
oneTensor.dtype

torch.float32

In [19]:
# Creating a range of tensors and tensors like
one_to_ten = torch.arange(0,10)
one_to_ten



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
start_end = torch.arange(start=0, end=1000, step=23)
start_end

tensor([  0,  23,  46,  69,  92, 115, 138, 161, 184, 207, 230, 253, 276, 299,
        322, 345, 368, 391, 414, 437, 460, 483, 506, 529, 552, 575, 598, 621,
        644, 667, 690, 713, 736, 759, 782, 805, 828, 851, 874, 897, 920, 943,
        966, 989])

In [21]:
#create a tensor with teh same size as some else tensor
like_tensor = torch.zeros_like(one_to_ten)
like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
like_tensor_ones_matrix = torch.ones_like(tensor)
like_tensor_ones_matrix

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])

In [23]:
#data types 
float_32_tensor = torch.tensor([1.,2.,3.],
                                dtype = None)
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = torch.tensor([1.,2.,3.],
                                dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [25]:
float_16_changer_tensor = float_32_tensor.type(torch.float16)
float_16_changer_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [30]:
random_tensor_10 = torch.rand(10,10)
random_tensor_10

tensor([[0.8551, 0.9745, 0.8084, 0.1066, 0.2999, 0.6545, 0.5947, 0.5718, 0.2143,
         0.7834],
        [0.9892, 0.1403, 0.3519, 0.4440, 0.8949, 0.8407, 0.6984, 0.4647, 0.4126,
         0.1163],
        [0.2197, 0.8836, 0.8585, 0.0196, 0.1652, 0.1634, 0.6412, 0.4747, 0.6811,
         0.2203],
        [0.4898, 0.5792, 0.1036, 0.0521, 0.7442, 0.5819, 0.1817, 0.7064, 0.4980,
         0.6133],
        [0.5857, 0.4213, 0.3473, 0.0421, 0.7950, 0.7473, 0.9545, 0.7529, 0.1058,
         0.7119],
        [0.8150, 0.5676, 0.5705, 0.3501, 0.4107, 0.4995, 0.4637, 0.6767, 0.4130,
         0.7524],
        [0.0257, 0.0377, 0.0196, 0.6327, 0.1150, 0.4755, 0.4878, 0.3837, 0.6964,
         0.3716],
        [0.8808, 0.0312, 0.5745, 0.7474, 0.4023, 0.4801, 0.6572, 0.4801, 0.4165,
         0.2373],
        [0.6679, 0.0391, 0.3701, 0.1135, 0.2050, 0.7121, 0.9490, 0.0647, 0.8802,
         0.7735],
        [0.5816, 0.6740, 0.3777, 0.9040, 0.5971, 0.7157, 0.2452, 0.1685, 0.1668,
         0.4975]])